# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

app_lucky_number:
    path: /mycv/number
    controller: App\Controller\MathildeController::number
    
create_formation:
    path: /create/formation
    controller: App\Controller\MathildeController::createformation
    
create_experience:
    path: /create/experience
    controller: App\Controller\MathildeController::createexperience
    
create_loisirs:
    path: /create/loisirs
    controller: App\Controller\MathildeController::createloisirs