# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

app_lucky_number:
    path: /mycv/number
    controller: App\Controller\MathildeController::number

create_contact:
    path: /create/contact
    controller: App\Controller\MathildeController::createcontact
    
create_formation:
    path: /create/formation
    controller: App\Controller\MathildeController::createformation
    
create_experience:
    path: /create/experience
    controller: App\Controller\MathildeController::createexperience
    
create_loisirs:
    path: /create/loisirs
    controller: App\Controller\MathildeController::createloisirs
    
formulaire_loisirs:
    path: /formulaire/loisirs
    controller: App\Controller\LoisirsController::create

valid_loisirs:
    path: /valid/loisirs
    controller: App\Controller\LoisirsController::valid

edit_loisirs:
    path: /edit/loisirs/{id}
    controller: App\Controller\LoisirsController::edit
    
formulaire_experience:
    path: /formulaire/experience
    controller: App\Controller\ExperienceController::create
    
valid_experience:
    path: /valid/experience
    controller: App\Controller\ExperienceController::valid

edit_experience:
    path: /edit/experience/{id}
    controller: App\Controller\ExperienceController::edit

formulaire_formation:
    path: /formulaire/formation
    controller: App\Controller\FormationController::create
    
valid_formation:
    path: /valid/formation
    controller: App\Controller\FormationController::valid

edit_formation:
    path: /edit/formation/{id}
    controller: App\Controller\FormationController::edit

remove_experience:
    path: /remove/experience/{id}
    controller: App\Controller\ExperienceController::remove

remove_formation:
    path: /remove/formation/{id}
    controller: App\Controller\FormationController::remove
    
remove_loisirs:
    path: /remove/loisirs/{id}
    controller: App\Controller\LoisirsController::remove
    
admin:
    path: /admin
    controller: App\Controller\MathildeController::admin


